version: "3.7"
services:
  mypostgres:
    image: postgres
    container_name: mypostgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Bob4158997"
      POSTGRES_DB: "ticketing-app(Project-Security)"
    ports:
      - "5435:5433"
    restart: always
    volumes:
      - initdb:/var/lib/postgresql/data
    networks:
      - webnet
  ticketing-app:
    build: .
    container_name: ticketing-app
    platform: linux/amd64
    ports:
      - "9055:8080"
    networks:
      - webnet
    depends_on:
      - mypostgres
networks:
  webnet:
    driver: bridge
volumes:
  initdb: